
pipeline {
    agent any

    tools {
        maven 'Maven_3.9.9'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out the code...'
            }
        }

        stage('Build') {
            steps {
                dir('Selenium_Project') {
                    bat 'mvn clean install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Selenium_Project') {
                    bat 'mvn test'
                }
            }
        }
        stage('Check test-output') {
    steps {
        dir('Selenium_Project') {
            bat 'dir test-output /s'
        }
    }
}

        stage('Deploy') {
            steps {
                echo 'Deploy step - add your deployment commands here'
            }
        }
    }

    post {
        always {
            echo 'Publishing TestNG HTML report...'
            publishHTML([
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'Selenium_Project/test-output', // adjust path if needed
                reportFiles: 'index.html',
                reportName: 'TestNG HTML Report'
            ])
             echo 'Publishing JUnit-compatible TestNG results...'
            junit 'Selenium_Project/test-output/testng-results.xml'
        }
    }
}
